### ISSUE TITLE
English translation? 

### ISSUE THREAD

**Issue by matej118111** [FoxyTheBot/Foxy#72]

**Comment by WinG4merBR** [comment]
Foxy's multi-language support is already in development

**Comment by Heryson1616** [comment]
SEXOOOOOOOOOOOO

**Comment by Heryson1616** [comment]
digo, SEEEEEEEXXXXXX

**Comment by WinG4merBR** [comment]
## 🎉 | Merged!

The pull request has already merged, wait that in a few weeks I will deploy in the Foxy

> Commit [d342999](https://github.com/FoxyTheBot/Foxy/commit/d342999dfb3191ad4074188c6cde76665b398498) 

If you need help, you can contact me at Discord! Win#6611
