### ISSUE TITLE
Edit the package.json file adding the build scripts

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [FoxyTheBot/Foxy#76]
The package.json file is without the build scripts, so there is no way to build the entire project and run the start script.

exemple:

```json
"scripts": {
  "build": "tsc --project ./tsconfig.json"
}
```

**Comment by WinG4merBR** [comment]
It is not necessary to use scripts, as you only type two commands in the shell! Unless you are lazy

**Comment by TiaGoiNsaNy** [comment]
It's not about being lazy, it's about automating the project.

**Comment by WinG4merBR** [comment]
To compile, it's simple to just type `tsc` than `npm run build`, I think you meant compile and run automatically

**Comment by TiaGoiNsaNy** [comment]
I know all the methods, but to make everything more automated, it would be necessary to add all the scripts inside the package.json

**Comment by WinG4merBR** [comment]
It is not necessary to add scripts in the package file, it is optional and not necessary.
